import type { GiftEntry } from "./types";

export const giftCatalog: GiftEntry[] = [
  {
    id: "001",
    title: "Leather-Bound Journal",
    description: "A high-quality leather journal with 200 pages of acid-free paper, perfect for writers and thinkers.",
    occasionTags: ["birthday", "graduation", "christmas", "any"],
    interestTags: ["writing", "journaling", "reading", "creativity"],
    priceMin: 25,
    priceMax: 45,
  },
  {
    id: "002",
    title: "Artisan Coffee Subscription",
    description: "3-month subscription to a specialty coffee roaster, with two bags of freshly roasted single-origin beans each month.",
    occasionTags: ["birthday", "christmas", "any"],
    interestTags: ["coffee", "food", "cooking", "beverages"],
    priceMin: 60,
    priceMax: 90,
  },
  {
    id: "003",
    title: "Yoga Starter Kit",
    description: "Premium yoga mat, two cork blocks, and a stretch strap — everything a beginner needs to get started.",
    occasionTags: ["birthday", "new-year", "any"],
    interestTags: ["yoga", "fitness", "wellness", "mindfulness"],
    priceMin: 55,
    priceMax: 80,
  },
  {
    id: "004",
    title: "Scratch-Off World Map",
    description: "A large, detailed world map print where you scratch off the gold foil to reveal places you've visited.",
    occasionTags: ["birthday", "graduation", "anniversary", "christmas"],
    interestTags: ["travel", "adventure", "maps", "decoration"],
    priceMin: 20,
    priceMax: 35,
  },
  {
    id: "005",
    title: "Kindle Paperwhite",
    description: "The latest Kindle with a glare-free display, adjustable warm light, and weeks of battery life.",
    occasionTags: ["birthday", "graduation", "christmas"],
    interestTags: ["reading", "books", "technology", "travel"],
    priceMin: 140,
    priceMax: 160,
  },
  {
    id: "006",
    title: "Gourmet Hot Sauce Set",
    description: "A curated collection of 6 artisan hot sauces ranging from smoky-mild to fiery-hot, in a handsome gift box.",
    occasionTags: ["birthday", "christmas", "any"],
    interestTags: ["cooking", "food", "spicy", "culinary"],
    priceMin: 30,
    priceMax: 50,
  },
  {
    id: "007",
    title: "Personalized Star Map",
    description: "A beautiful print showing the exact star alignment on any date and location you choose — birthdays, anniversaries, etc.",
    occasionTags: ["birthday", "anniversary", "valentines", "wedding"],
    interestTags: ["astronomy", "romance", "art", "decoration"],
    priceMin: 30,
    priceMax: 60,
  },
  {
    id: "008",
    title: "Wireless Noise-Cancelling Earbuds",
    description: "Premium true-wireless earbuds with active noise cancellation, 30-hour total battery, and IPX4 water resistance.",
    occasionTags: ["birthday", "graduation", "christmas"],
    interestTags: ["music", "technology", "fitness", "commuting"],
    priceMin: 80,
    priceMax: 130,
  },
  {
    id: "009",
    title: "Sourdough Baking Kit",
    description: "Everything to start sourdough from scratch: starter culture, banneton, lame, bench scraper, and recipe booklet.",
    occasionTags: ["birthday", "christmas", "any"],
    interestTags: ["baking", "cooking", "food", "DIY"],
    priceMin: 45,
    priceMax: 70,
  },
  {
    id: "010",
    title: "Hammock with Stand",
    description: "A portable Brazilian-style cotton hammock with a sturdy steel stand — no trees required.",
    occasionTags: ["birthday", "graduation", "any"],
    interestTags: ["outdoors", "camping", "relaxation", "garden"],
    priceMin: 90,
    priceMax: 140,
  },
  {
    id: "011",
    title: "Indoor Herb Garden Kit",
    description: "Self-watering planter with organic seeds for basil, mint, cilantro, and parsley, plus coconut-coir growing medium.",
    occasionTags: ["birthday", "housewarming", "any"],
    interestTags: ["gardening", "cooking", "plants", "home"],
    priceMin: 30,
    priceMax: 50,
  },
  {
    id: "012",
    title: "Watercolor Paint Set",
    description: "Professional-grade 48-color watercolor set with two brushes and a watercolor paper pad.",
    occasionTags: ["birthday", "christmas", "graduation"],
    interestTags: ["art", "painting", "creativity", "craft"],
    priceMin: 35,
    priceMax: 55,
  },
  {
    id: "013",
    title: "Cast Iron Skillet",
    description: "A 10-inch pre-seasoned cast iron skillet — the kitchen workhorse that lasts a lifetime.",
    occasionTags: ["birthday", "housewarming", "christmas", "wedding"],
    interestTags: ["cooking", "food", "kitchen", "culinary"],
    priceMin: 25,
    priceMax: 45,
  },
  {
    id: "014",
    title: "Escape Room Experience",
    description: "A gift card for two at a local escape room, perfect for couples or adventurous friends.",
    occasionTags: ["birthday", "anniversary", "valentines", "any"],
    interestTags: ["puzzles", "games", "adventure", "social"],
    priceMin: 50,
    priceMax: 80,
  },
  {
    id: "015",
    title: "Succulent Terrarium Kit",
    description: "Glass geometric terrarium with a hand-picked selection of miniature succulents and decorative pebbles.",
    occasionTags: ["birthday", "housewarming", "any"],
    interestTags: ["plants", "gardening", "decoration", "home"],
    priceMin: 25,
    priceMax: 45,
  },
  {
    id: "016",
    title: "Smart LED Desk Lamp",
    description: "Touch-dimmable lamp with color temperature adjustment (2700K–6500K), USB-C charging port, and eye-care mode.",
    occasionTags: ["birthday", "graduation", "back-to-school"],
    interestTags: ["technology", "productivity", "home", "study"],
    priceMin: 40,
    priceMax: 65,
  },
  {
    id: "017",
    title: "Vintage Board Game Bundle",
    description: "Classic strategy games — Settlers of Catan, Ticket to Ride, and Pandemic — in a gift set.",
    occasionTags: ["birthday", "christmas", "any"],
    interestTags: ["games", "social", "strategy", "family"],
    priceMin: 90,
    priceMax: 130,
  },
  {
    id: "018",
    title: "Luxury Bath Bomb Set",
    description: "12 hand-made bath bombs in lavender, eucalyptus, rose, and citrus scents, packaged in a keepsake box.",
    occasionTags: ["birthday", "valentines", "mothers-day", "any"],
    interestTags: ["wellness", "self-care", "relaxation", "beauty"],
    priceMin: 20,
    priceMax: 40,
  },
  {
    id: "019",
    title: "Camping Cookware Set",
    description: "Lightweight anodized aluminum 10-piece cookware set — pots, pans, plates, and utensils — all nesting for easy packing.",
    occasionTags: ["birthday", "graduation", "any"],
    interestTags: ["camping", "outdoors", "hiking", "cooking"],
    priceMin: 50,
    priceMax: 80,
  },
  {
    id: "020",
    title: "Personalised Recipe Book",
    description: "A blank hardcover book to fill with family recipes, with prompt pages and photo pockets.",
    occasionTags: ["birthday", "mothers-day", "christmas", "any"],
    interestTags: ["cooking", "family", "writing", "food"],
    priceMin: 25,
    priceMax: 40,
  },
  {
    id: "021",
    title: "Electric Bike Accessory Kit",
    description: "A curated set of cycling accessories: a phone mount, a saddle bag, a multi-tool, and a high-visibility vest.",
    occasionTags: ["birthday", "any"],
    interestTags: ["cycling", "fitness", "commuting", "outdoors"],
    priceMin: 40,
    priceMax: 70,
  },
  {
    id: "022",
    title: "Language Learning App Subscription",
    description: "12-month premium subscription to a top language-learning app — perfect for aspiring multilingualists.",
    occasionTags: ["birthday", "graduation", "new-year"],
    interestTags: ["languages", "learning", "travel", "education"],
    priceMin: 50,
    priceMax: 80,
  },
  {
    id: "023",
    title: "Cocktail-Making Masterclass",
    description: "Online bartending course with 60+ video lessons covering classic and modern cocktails, plus technique deep-dives.",
    occasionTags: ["birthday", "christmas", "any"],
    interestTags: ["cocktails", "beverages", "social", "learning"],
    priceMin: 30,
    priceMax: 60,
  },
  {
    id: "024",
    title: "Puzzle — 1000-Piece Landscape",
    description: "A high-quality 1000-piece jigsaw with a stunning national-park landscape print.",
    occasionTags: ["birthday", "christmas", "any"],
    interestTags: ["puzzles", "relaxation", "nature", "home"],
    priceMin: 20,
    priceMax: 35,
  },
  {
    id: "025",
    title: "Stainless Steel Water Bottle",
    description: "Vacuum-insulated 32 oz bottle that keeps drinks cold 24 hrs / hot 12 hrs, with a wide-mouth lid.",
    occasionTags: ["birthday", "graduation", "any"],
    interestTags: ["fitness", "outdoors", "sustainability", "travel"],
    priceMin: 25,
    priceMax: 40,
  },
];

export function searchCatalog(
  occasionTags: string[],
  interestTags: string[],
  budgetMin: number,
  budgetMax: number
): GiftEntry[] {
  return giftCatalog.filter((gift) => {
    const occasionMatch =
      occasionTags.length === 0 ||
      occasionTags.some((t) => gift.occasionTags.includes(t.toLowerCase()));
    const interestMatch =
      interestTags.length === 0 ||
      interestTags.some((t) => gift.interestTags.includes(t.toLowerCase()));
    const priceMatch = gift.priceMin <= budgetMax && gift.priceMax >= budgetMin;
    return occasionMatch && interestMatch && priceMatch;
  });
}
